apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wzjq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wzjq
    app.kubernetes.io/part-of: e2e-nodejs
  name: devfile-sample-wzjq
  namespace: e2e-demos-bvlf-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-wzjq
status:
  loadBalancer: {}
